# Generated by Django 4.1.7 on 2023-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('velo', 'velo'), ('e-velo', 'velp electrique'), ('e-scotter', 'scotter electrique'), ('Accesoires', 'Accesoires')], max_length=255)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
