# Generated by Django 4.1.7 on 2023-03-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('category_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('icon', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('featured_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_product', to='product.product')),
            ],
        ),
    ]
