# Generated by Django 4.1.7 on 2023-03-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
