# Generated by Django 4.1.7 on 2023-04-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('velo', 'velo'), ('e-velo', 'velo electrique'), ('e-scotter', 'scotter electrique'), ('Accesoires', 'Accesoires')], max_length=20),
        ),
    ]
