# Generated by Django 4.1.7 on 2023-04-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.promotion'),
            preserve_default=False,
        ),
    ]
