# Generated by Django 4.1.7 on 2023-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_promotion_alter_promotion_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percentage',
        ),
    ]
